apiVersion: apps/v1
kind: Deployment
metadata:
  name: treehouse-deployment
  namespace: gallifrey
  labels:
    app: treehouse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treehouse
  template:
    metadata:
      labels:
        app: treehouse
    spec:
      containers:
      - name: treehouse
        image: nicokahlert/gallifrey-treehouse@sha256:585b08f399df17985c78fbe09f0d850e890a29084cedf74300ed5e7cfee2a0cc
        volumeMounts:
        - mountPath: /etc/treehouse
          name: treehouse-config-vol
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 10Mi
      volumes:
      - name: treehouse-config-vol
        configMap:
          name: gallifrey-config

      
