apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: "2019-11-16T12:44:11Z"
  generation: 7
  labels:
    app: frontend
  name: frontend-deployment
  namespace: gallifrey
  resourceVersion: "144406"
  selfLink: /apis/apps/v1/namespaces/gallifrey/deployments/frontend-deployment
  uid: 759f6c10-c0c9-4df0-afce-ad40d91e1d2b
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: nicokahlert/gallifrey-frontend@sha256:52d3ab15ae9213d045b6cff76ab5bc6ee0e817fe047506e5f41653f21436e089
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2019-11-16T12:44:11Z"
    lastUpdateTime: "2019-11-17T13:52:01Z"
    message: ReplicaSet "frontend-deployment-c99679458" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-11-18T07:46:30Z"
    lastUpdateTime: "2019-11-18T07:46:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 7
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
