apiVersion: apps/v1
kind: Deployment
metadata:
  name: treehouse-deployment
  namespace: gallifrey
  labels:
    app: treehouse
spec:
  replicas: 5
  selector:
    matchLabels:
      app: treehouse
  template:
    metadata:
      labels:
        app: treehouse
    spec:
      containers:
      - name: treehouse
        image: nicokahlert/gallifrey-treehouse@sha256:3fe4e76bc3663a3820e818e5af110525bcc84fb3937c5e64b792190f8004e59e
        volumeMounts:
        - mountPath: /etc/treehouse
          name: treehouse-config-vol
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      volumes:
      - name: treehouse-config-vol
        configMap:
          name: treehouse-config

      
