apiVersion: apps/v1
kind: Deployment
metadata:
  name: treehouse-deployment
  namespace: gallifrey
  labels:
    app: treehouse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: treehouse
  template:
    metadata:
      labels:
        app: treehouse
    spec:
      containers:
      - name: treehouse
        image: nicokahlert/gallifrey-treehouse:latest
        volumeMounts:
        - mountPath: /etc/treehouse
          name: treehouse-config-vol
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      volumes:
      - name: treehouse-config-vol
        configMap:
          name: treehouse-config

      
