source 'https://rubygems.org' do
  gem 'aws-sdk-s3'
  gem 'json'
  gem 'mysql2'
  gem 'ruby-filemagic'
  gem 'rubysl-securerandom'
  gem 'rubysl-yaml'
  gem 'sinatra'
  gem 'sinatra-cross_origin'
end
