apiVersion: v1
kind: Service
metadata:
  name: oauth-server
  namespace: gallifrey
spec:
  ports:
  - port: 80
    name: auth
    targetPort: oauth-port
  selector:
    app: oauth
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: gallifrey
  name: oauth
spec:
  selector:
    matchLabels:
      app: oauth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
      - name: oauth-server
        image: babelouest/glewlwyd
        ports:
        - name: oauth-port
          containerPort: 4593
          protocol: TCP  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth-ingress
  namespace: gallifrey
spec:
  rules:
  - host: auth.gallifrey.local
    http:
      paths:
      - path: /
        backend:
          serviceName: oauth-server
          servicePort: auth