apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: infra
  labels:
    app: registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-data
        ports:
        - containerPort:  5000
      volumes:
       - name: registry-data
         hostPath:
           path: /k8s/registry
           type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: registry-service
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: infra
spec:
  rules:
  - host: registry.gallifrey.local
    http:
      paths:
      - path: /
        backend:
          serviceName: registry-service
          servicePort: 5000
