apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gallifrey
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: frontend
        image: nicokahlert/gallifrey-frontend@sha256:ec0c940c848dd7c8cf0e8f1b9d0a5e388b6b355ef936dd58ec56f13320185a0f
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 50Mi