apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gallifrey
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: frontend
        image: nicokahlert/gallifrey-frontend@sha256:78c7d0aeaaac2fbb80acfff0e95b462e4e2e958b8b4e15de6b476ab53980c5d0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          request:
            cpu: 20m
            memory: 50Mi