apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gallifrey
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: frontend
        image: nicokahlert/gallifrey-frontend@sha256:66a89f9ec0bf683b15ca9c46fd51d037e09d51cf97274771fe4c5dd9684176ac
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 50Mi