apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gallifrey
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: frontend
        image: nicokahlert/gallifrey-frontend@sha256:be3e13de65582bd693258c5e5358c4108646ea0214ac624d35c21ab2c96ed6b6
        ports:
        - containerPort: 80
        imagePullPolicy: Always