apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gallifrey
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: frontend
        image: nicokahlert/gallifrey-frontend@sha256:23b89a8704feed1f109183fea6210163481fa33c8f96a1568ad75413d10cc967
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 50Mi