apiVersion: v1
kind: Service
metadata:
  name: oauth-server
  namespace: gallifrey
spec:
  ports:
  - port: 8080
    name: auth
    targetPort: auth
  selector:
    app: oauth
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: gallifrey
  name: oauth
spec:
  selector:
    matchLabels:
      app: oauth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
      - name: oauth-server
        image: jboss/keycloak
        env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: start-123 
        - name: KEYCLOAK_FRONTEND_URL
          value: auth.gallifrey.local
        - name: KEYCLOAK_HOSTNAME
          value: keycloak.local 
        - name: KEYCLOAK_HTTP_PORT
          value: 8080
        ports:
        - name: keycloak
          containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth-ingress
  namespace: gallifrey
spec:
  rules:
  - host: auth.gallifrey.local
    http:
      paths:
      - path: /
        backend:
          serviceName: oauth-server
          servicePort: 80