apiVersion: v1
kind: Service
metadata:
  name: oauth-server
  namespace: gallifrey
spec:
  ports:
  - port: 80
    name: auth
    targetPort: oauth-port
  selector:
    app: oauth
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: gallifrey
  name: oauth
spec:
  selector:
    matchLabels:
      app: oauth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
      - name: oauth-server
        image: babelouest/glewlwyd
        ports:
        - name: oauth-port
          containerPort: 4593
          protocol: TCP
        volumeMounts:
          - name: oauth-server-config 
            mountPath: /etc/glewlwyd  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth-ingress
  namespace: gallifrey
spec:
  rules:
  - host: auth.gallifrey.local
    http:
      paths:
      - path: /
        backend:
          serviceName: oauth-server
          servicePort: auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-server-config
data: |
port=4593
external_url="http://localhost:4593"
login_url="login.html"
url_prefix="api"
static_files_path="/usr/share/glewlwyd/webapp/"
allow_origin="*"
log_mode="console"
log_level="DEBUG"
log_file="/var/log/glewlwyd.log"
cookie_secure=0
session_expiration=2419200
session_key="GLEWLWYD2_SESSION_ID"
admin_scope="g_admin"
profile_scope="g_profile"
user_module_path="/usr/lib/glewlwyd/user"
client_module_path="/usr/lib/glewlwyd/client"
user_auth_scheme_module_path="/usr/lib/glewlwyd/scheme"
plugin_module_path="/usr/lib/glewlwyd/plugin"
use_secure_connection=false
secure_connection_key_file="/etc/glewlwyd/server.key"
secure_connection_pem_file="/etc/glewlwyd/server.crt"
secure_connection_ca_file="/etc/glewlwyd/ca.crt"
hash_algorithm = "SHA512"
}
static_files_mime_types =
(
  {
    extension = ".html"
    mime_type = "text/html"
  },
  {
    extension = ".css"
    mime_type = "text/css"
  },
  {
    extension = ".js"
    mime_type = "application/javascript"
  },
  {
    extension = ".json"
    mime_type = "application/json"
  },
  {
    extension = ".png"
    mime_type = "image/png"
  },
  {
    extension = ".jpg"
    mime_type = "image/jpeg"
  },
  {
    extension = ".jpeg"
    mime_type = "image/jpeg"
  },
  {
    extension = ".ttf"
    mime_type = "font/ttf"
  },
  {
    extension = ".woff"
    mime_type = "font/woff"
  },
  {
    extension = ".woff2"
    mime_type = "font/woff2"
  },
  {
    extension = ".map"
    mime_type = "application/octet-stream"
  },
  {
    extension = ".ico"
    mime_type = "image/x-icon"
  }
) 